### ISSUE TITLE
FB Login not working

### ISSUE THREAD

**Issue by mc51** [jcrodriguez1989/Rtinder#1]
Great project, thanks for your effort. I've tried checked everything out using SMS-Auth and it works great!

However, there is an issue using the FB login method. It seems that FB has changed something recently. The access token returned by the `configAccount('User', 'PW')` function is a HTML response:
`accesstoken <- '<!DOCTYPE html><html><head><title>Error</title> [...]`

You find the whole output here: https://pastebin.com/nkaKRkqV

Other similar projects seem to also be affected:
https://github.com/fbessez/Tinder/issues/75
https://github.com/Vikash-Kothary/tinder-api-python/issues/6

**Comment by jcrodriguez1989** [comment]
Hi @mc51 , thanks for reporting this issue.
Just to mention, the issue is for getting the token, if you have done this before, then you just have to use the `login()` method from now on.

Apparently, the official tinder web app is having this issue, and thus, we are not being able to get the token through the API.
You could check this out by trying to log in through Facebook at https://tinder.com/
We will have to wait until tinder fixes this.

best,
Juan Cruz

**Comment by mc51** [comment]
Thanks for the quick reply. However, I was able to manually obtain the FB Token. Thus, I'm not too sure this really is an issue with the tinder page. Using this url:

> https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&scope=user_birthday%2Cuser_photos%2Cuser_education_history%2Cemail%2Cuser_relationship_details%2Cuser_friends%2Cuser_work_history%2Cuser_likes&response_type=token%2Csigned_request&client_id=464891386855067&ret=login&fallback_redirect_uri=221e1158-f2e9-1452-1a05-8983f99f7d6e&ext=1556057433&hash=Aea6jWwMP_tDMQ9y

When navigating to this link (while logged in to FB), I received the FB popup asking to allow Tinder access. After clicking on the OK button, I get a response including the access_token.

**Comment by mc51** [comment]
What I did manually, is done programmatically here:

https://github.com/jaebradley/tinder-access-token-generator/commit/2e94717bb53a5074a2565c8725e9e9c076148c5b

I think, this is the right way to do it currently. So adjusting to this flow should fix the issue.

**Comment by jcrodriguez1989** [comment]
thank you very much @mc51 !!
I got it fixed in the last commit. Could you check it out?

**Comment by mc51** [comment]
@jcrodriguez1989 wow, that was fast. For me, it works now!
