### ISSUE TITLE
changeSettings does not work

### ISSUE THREAD

**Issue by RizenBy** [jcrodriguez1989/Rtinder#2]
thank you so much for this wonderful package.
Unfortunately, updating my own account setting doesn't seem to work. 
I get my account object back without an error message, but the changes will not be transferred either.
Rest works.
Do you have any idea what could be wrong with that?
Best Andi

**Comment by jcrodriguez1989** [comment]
@RizenBy thanks for reporting this bug.
Could you please try with the new version?
`remotes::install_github("jcrodriguez1989/Rtinder")`

**Comment by RizenBy** [comment]
Works perfect ! 
Thank you very much.
